# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Darkwinds
email: hello@mego.cl
description: > # this means to ignore newlines until "baseurl:"
  The epic pirate battle on the blockchain
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://playdarkwinds.com" # the base hostname & protocol for your site
twitter_username: playdarkwinds
github_username:  megoforce

# Build settings
markdown: kramdown
